apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
  labels:
    app: sample-app
spec:
  containers:
    - name: main
      image: sample-app:ver1
      ports:
        - containerPort: 80
      resources:
        requests:
          memory: 10Mi #important one
          cpu: 10m #have some point and trick
        limits:
          memory: 20Mi
          cpu: 20m